config/routes.rb
Rails.application.routes.draw do
  post "headshot/capture" => 'headshot#capture', :as => :headshot_capture

  namespace :admin do
    get "/dashboard", to: "dashboard#show"
    resources :categories, only: [:index, :create, :edit, :update, :destroy]
    resources :staches, only: [:new, :create, :index, :edit, :destroy, :update]
    resources :orders, only: [:show]
    put "cancel_order", to: "orders#cancel"
    put "paid_order", to: "orders#paid"
    put "complete_order", to: "orders#complete"
    put "retire_stache", to: "staches#retire"
    put "activate_stache", to: "staches#activate"
  end

  resources :staches, only: [:index, :show] do
    get "stached", to: "staches#stached"
  end

  resources :cart_staches, only: [:create, :destroy]
  resource :cart, only: [:show]
  resources :categories, only: [:index, :show]
  resources :users, only: [:new, :create, :edit, :update]
  resources :orders, only: [:index, :show, :new, :create]

  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"
  get "/dashboard", to: "users#show"
  post "update_quantity", to: "cart_staches#update_quantity"
  get "/about", to: "static#about"

  root "categories#index"
end

app/models/cart.rb
class Cart
  attr_reader :contents

  def initialize(initial_contents)
    @contents = initial_contents || {}
  end

  def add_stache(stache_id)
    contents[stache_id.to_s] ||= 0
    contents[stache_id.to_s] += 1
  end

  def delete_stache(stache_id)
    contents.delete(stache_id.to_s)
  end

  def staches
    Stache.find(contents.keys)
  end

  def stache_cost(stache_id)
    Stache.find(stache_id).price * contents[stache_id.to_s]
  end

  def total_quantity
    contents.values.sum
  end

  def total_cost
    costs = contents.map do
              |stache_id, quantity| Stache.find(stache_id).price * quantity
    end
    costs.sum
  end
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :stache_categories
  has_many :staches, through: :stache_categories
  validates :title, uniqueness: true, presence: true
end

app/models/headshot_photo.rb
class HeadshotPhoto < ActiveRecord::Base
  belongs_to :capturable, :polymorphic => true
  after_create :set_user

  def set_user
    User.current_user.headshot_photos << self
  end
end

app/models/order.rb
class Order < ActiveRecord::Base
  belongs_to :user
  has_many :order_staches
  has_many :staches, through: :order_staches
  before_create :set_ordered_status

  validates :zipcode, presence: true, length: { is: 5 }, numericality: true
  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :address, presence: true
  validates :city, presence: true
  validates :state, presence: true
  validates_inclusion_of :status,
                         in: %w(ordered paid completed cancelled)

  def set_ordered_status
    self.status ||= "ordered"
  end

  def total
    staches.map { |stache| subtotal(stache) }.sum
  end

  def quantity(stache)
    order_staches.find_by(stache_id: stache.id).quantity
  end

  def subtotal(stache)
    quantity(stache) * stache.price
  end

  def completed?
    %w(completed cancelled).include?(status) ? "Yes" : "No"
  end

  def formatted_created_date
    date = created_at.in_time_zone("Mountain Time (US & Canada)")
    date.strftime("%m/%d/%Y at %I:%M %p")
  end

  def formatted_updated_date
    date = updated_at.in_time_zone("Mountain Time (US & Canada)")
    date.strftime("%m/%d/%Y at %I:%M %p")
  end

  def create_order_staches(cart)
    cart.each do |stache_id, quantity|
      order_staches.create(stache_id: stache_id, quantity: quantity)
    end
  end

  def ordered?
    status == "ordered"
  end

  def paid?
    status == "paid"
  end

  def self.order_status_count
    status_freq = group(:status).count
    %w(ordered paid completed cancelled).each do |status|
      status_freq[status] ||= 0
    end
    status_freq.map { |status, count| [status.capitalize, count] }
  end
end

app/models/order_placement.rb
class OrderPlacement
  attr_reader :order, :cart

  def initialize(order, cart)
    @order = order
    @cart = cart
  end

  def create
    if order.save
      order.create_order_staches(cart)
    end
  end
end

app/models/order_stache.rb
class OrderStache < ActiveRecord::Base
  belongs_to :order
  belongs_to :stache

  validates :quantity, presence: true,
                       numericality: { greater_than_or_equal_to: 0 }
end

app/models/stache.rb
class Stache < ActiveRecord::Base
  has_many :stache_categories
  has_many :categories, through: :stache_categories
  has_many :order_staches
  has_many :orders, through: :order_staches
  validates :name, presence: true, uniqueness: true
  validates :description, presence: true
  validates :price, presence: true,
                    numericality: { greater_than_or_equal_to: 0.0 }
  validates :categories, presence: true
  after_create :default_image

  def status
    if retired?
      "Retired"
    else
      "Active"
    end
  end

  def truncated_description
    description[0..200] + "..."
  end

  private

  def default_image
    if image_url.nil? || image_url.empty?
      self.image_url = "http://i.imgur.com/kMx8J0g.png"
    end
  end
end

app/models/stache_category.rb
class StacheCategory < ActiveRecord::Base
  belongs_to :stache
  belongs_to :category
end

app/models/stache_creation.rb
class StacheCreation
  attr_reader :stache, :categories, :status

  def initialize(stache, categories, status)
    @stache = stache
    @categories = categories
    @status = status
  end

  def create
    if status == 1
      @stache.retired = true
    end
    @stache.categories << Category.find(categories) unless categories.nil?
    stache.save
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :orders
  has_many :headshot_photos, :as => :capturable
  validates :username, presence: true, uniqueness: true
  enum role: %w(default admin)
  has_secure_password

  def self.current_user
    Thread.current[:current_user]
  end

  def self.current_user=(usr)
    Thread.current[:current_user] = usr
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  def show
    @staches = @cart.staches
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :check_current_user

  def index
    @orders = current_user.orders
  end

  def show
    @order = current_user.orders.find(params[:id])
  end

  def new
    @order = Order.new
  end

  def create
    @order = current_user.orders.new(order_params)
    @order_placement = OrderPlacement.new(@order, @cart.contents)
    if @order_placement.create
      flash[:order_notice] = "Order was successfully placed."
      session[:cart] = {}
      redirect_to order_path(@order)
    else
      render :new
    end
  end

  private

  def order_params
    params.require(:order).permit(:first_name, :last_name, :address,
                                  :city, :state, :zipcode)
  end
end

app/controllers/staches_controller.rb
class StachesController < ApplicationController
  helper :headshot

  def index
    @staches = Stache.all
  end

  def show
    @stache = Stache.find(params[:id])
    session[:cam_stache_id] = @stache.id
  end

  def stached
    @stache = Stache.find(params[:stache_id])
    @photo = current_user.headshot_photos.last
  end

end

app/controllers/static_controller.rb
class StaticController < ApplicationController
  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  helper :headshot
  before_action :current_user_guard, only: [:edit]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      User.current_user = User.find(session[:user_id])
      redirect_to dashboard_path
    else
      render :new
    end
  end

  def show
    @user = current_user
    render :dashboard
  end

  def edit
    @user = current_user
  end

  def update
    @user = current_user
    if @user.update(user_params)
      redirect_to dashboard_path
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:username, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/cartstaches_helper.rb
module CartstachesHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/staches_helper.rb
module StachesHelper
end

app/views/admin/dashboard.html.erb
<div id="admin-orders-table" class="container">
  <h4>Admin StacheBoard</h4>
  <%= link_to "Create New Stache", new_admin_stache_path, class: "btn light-green darken-4" %>
  <%= link_to "View All Staches", admin_staches_path, class: "btn light-green darken-4" %>
  <%= link_to "View All Categories", admin_categories_path, class: "btn light-green darken-4" %>
  <div class="container">
    <h5 class="center">Order Statuses</h5>
    <%= bar_chart Order.order_status_count, discrete: true,
    colors: ["#33691e"],
    library: { backgroundColor: "transparent",
               hAxis: {title: "Frequency"}} %>
  </div>
  <h5 class="center">All Orders</h5>
  <a class='dropdown-button btn right light-green darken-3' href='#'
      data-activates='dropdown1'>Filter Order Status</a>
  <ul id='dropdown1' class='dropdown-content'>
    <li><%= link_to "All", admin_dashboard_path,
            class: "light-green-text darken-4-text" %></li>
    <li><%= link_to "Ordered", admin_dashboard_path(status: "ordered"),
            class: "light-green-text darken-4-text" %></li>
    <li><%= link_to "Paid", admin_dashboard_path(status: "paid"),
            class: "light-green-text darken-4-text" %></li>
    <li><%= link_to "Completed", admin_dashboard_path(status: "completed"),
            class: "light-green-text darken-4-text" %></li>
    <li><%= link_to "Cancelled", admin_dashboard_path(status: "cancelled"),
            class: "light-green-text darken-4-text" %></li>
  </ul>

  <table>
    <thead>
      <tr>
          <th data-field="id">Order Number</th>
          <th data-field="status">Status</th>
          <th data-field="update-status">Change Status:</th>
      </tr>
    </thead>

    <tbody>
      <% @orders.each do |order| %>
      <tr id=<%="order-#{order.id}"%>>
        <td><%= link_to "Order-#{order.id}", admin_order_path(order),
                id: "order-#{order.id}-link",
                class: "btn light-green darken-4" %></td>
        <td><%= order.status.capitalize %></td>
        <td>
          <% if order.ordered? %>
            <%= link_to "Cancel", admin_cancel_order_path(order_id: order.id),
                method: :put, id: "order-#{order.id}-cancel",
                class: "btn light-green darken-4" %>
            <%= link_to "Mark As Paid",
                admin_paid_order_path(order_id: order.id), method: :put,
                id: "order-#{order.id}-paid", class: "btn light-green darken-4" %>
          <% end %>
          <% if order.paid? %>
            <%= link_to "Cancel", admin_cancel_order_path(order_id: order.id),
                method: :put, id: "order-#{order.id}-cancel",
                class: "btn light-green darken-4" %>
            <%= link_to "Mark As Complete",
                admin_complete_order_path(order_id: order.id), method: :put,
                id: "order-#{order.id}-complete", class: "btn light-green darken-4" %>
          <% end %>
        </td>
      </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>LittleShopPrivateStache</title>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.5/css/materialize.min.css">
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  <link href='https://fonts.googleapis.com/css?family=Architects+Daughter' rel='stylesheet' type='text/css'>
  <link href='https://fonts.googleapis.com/css?family=Montserrat|Kameron|Unica+One' rel='stylesheet' type='text/css'>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag "//www.google.com/jsapi", "chartkick" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="nav-wrapper">
    <div class="right-nav">
      <% if current_user %>
        <%= link_to "Logout", logout_path, method: :delete, class: "right brown-text login-logout" %>
        <%= link_to "Orders", orders_path, class:"right brown-text login-logout" %>
        <%= link_to "Account", dashboard_path, class:"right brown-text login-logout" %>
        <%= link_to "Stacheboard", admin_dashboard_path, class:"right brown-text login-logout" if current_admin? %>
      <% else %>
        <%= link_to "Login", login_path, id: "Login", class:"right brown-text login-logout" %>
        <% unless request.path == new_user_path || request.path == login_path %>
          <%= link_to "Create Account", new_user_path, class: "right brown-text login-logout" %>
          <% end %>
      <% end %>
      <% if current_user %>
      <div id="credentials" class="brown-text hide-on-small-only">Logged In As: <%= current_user.username %> </div>
      <% end %>
    </div>

    <div class="left-nav">
      <%= link_to "Categories", categories_path, class:"brown-text fixed" %>
      <%= link_to "Staches", staches_path, class:"brown-text fixed" %>
      <% unless request.path == cart_path %>
      <div class="cart_box">
        <a id="View Cart" href="/cart"><i class="material-icons shoppingcart black-text">shopping_cart</i></a>
        <a class="cart_total" href="/cart">(<%= @cart.total_quantity %>)</a>
      </div>
      <% end %>
    </div>
    <div class="logo-box">
      <a href="/"><img class="responsive-img" src=" <%=random_stache%> " id="logo"/></a>
    </div>
  </div>

<% flash.each do |type, msg| %>
  <%= content_tag :div, sanitize(msg), class: "flash_#{type} flash" %>
<% end %>

<%= yield %>
<br><br><br><br><br>
<footer class="footer-bar">
  <div class="footer-content">
    <p class="black-text text-lighten-5 footer-content hide-on-small-only">
      put some hair on your lip...
    </p>
    <a href="/"><h5 class="white-text footer-content">Private Stache  </h5></a>
  </div>
  <a class="white-text footer-link" href="/about">About Us</a>
</footer>

<script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.5/js/materialize.min.js"></script>

</body>
</html>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <p><%= pluralize(object.errors.count, "error") %>
  prohibited this record from being saved:</p>
  <% object.errors.full_messages.each do |message| %>
    <li><%= message %></li>
  <% end %>
<% end %>