config/routes.rb
Rails.application.routes.draw do
  post "headshot/capture" => 'headshot#capture', :as => :headshot_capture

  namespace :admin do
    get "/dashboard", to: "dashboard#show"
    resources :categories, only: [:index, :create, :edit, :update, :destroy]
    resources :staches, only: [:new, :create, :index, :edit, :destroy, :update]
    resources :orders, only: [:show]
    put "cancel_order", to: "orders#cancel"
    put "paid_order", to: "orders#paid"
    put "complete_order", to: "orders#complete"
    put "retire_stache", to: "staches#retire"
    put "activate_stache", to: "staches#activate"
  end

  resources :staches, only: [:index, :show] do
    get "stached", to: "staches#stached"
  end

  resources :cart_staches, only: [:create, :destroy]
  resource :cart, only: [:show]
  resources :categories, only: [:index, :show]
  resources :users, only: [:new, :create, :edit, :update]
  resources :orders, only: [:index, :show, :new, :create]

  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"
  get "/dashboard", to: "users#show"
  post "update_quantity", to: "cart_staches#update_quantity"
  get "/about", to: "static#about"

  root "categories#index"
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :orders
  has_many :headshot_photos, :as => :capturable
  validates :username, presence: true, uniqueness: true
  enum role: %w(default admin)
  has_secure_password

  def self.current_user
    Thread.current[:current_user]
  end

  def self.current_user=(usr)
    Thread.current[:current_user] = usr
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  helper :headshot
  before_action :current_user_guard, only: [:edit]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      User.current_user = User.find(session[:user_id])
      redirect_to dashboard_path
    else
      render :new
    end
  end

  def show
    @user = current_user
    render :dashboard
  end

  def edit
    @user = current_user
  end

  def update
    @user = current_user
    if @user.update(user_params)
      redirect_to dashboard_path
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:username, :password, :password_confirmation)
  end
end

app/views/users/dashboard.html.erb
<div class="container">
  <h4>Your StacheBoard</h4>
  <p>
    Welcome <%= @user.username %>!
  </p>
  <%= link_to "Order History", orders_path, class: "btn light-green darken-4" %>

  <%= link_to "Edit Account Info", edit_user_path(@user), class: "btn light-green darken-4" %>
</div>

app/views/users/edit.html.erb
<div class="container">
  <h4>Edit Account Info</h4>
  <%= form_for(@user) do |f| %>
    <%= render "shared/error_messages", object: f.object %>

    <%= f.label :username %>
    <%= f.text_field :username  %>
    <br>

    <%= f.label :password %>
    <%= f.password_field :password %>
    <br>

    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation %>

    <%= f.submit "Update Account", class: "wave-effect waves-light btn light-green darken-4" %>
  <% end  %>
</div>

app/views/users/new.html.erb
<div class="container">
  <h4>Create a New Account</h4>
  <%= form_for(@user) do |f| %>

    <%= render "shared/error_messages", object: f.object %>

    <%= f.label :username %>
    <%= f.text_field :username  %>
    <br>

    <%= f.label :password %>
    <%= f.password_field :password %>
    <br>

    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation %>

    <%= f.submit "Create Account", class: "wave-effect waves-light btn light-green darken-4" %>
  <% end  %>
</div>