config/routes.rb
Rails.application.routes.draw do
  post "headshot/capture" => 'headshot#capture', :as => :headshot_capture

  namespace :admin do
    get "/dashboard", to: "dashboard#show"
    resources :categories, only: [:index, :create, :edit, :update, :destroy]
    resources :staches, only: [:new, :create, :index, :edit, :destroy, :update]
    resources :orders, only: [:show]
    put "cancel_order", to: "orders#cancel"
    put "paid_order", to: "orders#paid"
    put "complete_order", to: "orders#complete"
    put "retire_stache", to: "staches#retire"
    put "activate_stache", to: "staches#activate"
  end

  resources :staches, only: [:index, :show] do
    get "stached", to: "staches#stached"
  end

  resources :cart_staches, only: [:create, :destroy]
  resource :cart, only: [:show]
  resources :categories, only: [:index, :show]
  resources :users, only: [:new, :create, :edit, :update]
  resources :orders, only: [:index, :show, :new, :create]

  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"
  get "/dashboard", to: "users#show"
  post "update_quantity", to: "cart_staches#update_quantity"
  get "/about", to: "static#about"

  root "categories#index"
end

app/controllers/admin/staches_controller.rb
module Admin
  class StachesController < Admin::BaseController
    def new
      @stache = Stache.new
    end

    def create
      categories = params[:stache][:categories]
      retired_status = params[:stache][:retired]
      @stache = Stache.new(stache_params)
      @stache_creation = StacheCreation.new(@stache, categories, retired_status)
      if @stache_creation.create
        flash[:notice] = "#{@stache.name} created!"
        redirect_to @stache
      else
        render :new
      end
    end

    def index
      @staches = Stache.all.includes(:categories)
    end

    def edit
      @stache = Stache.find(params[:id])
    end

    def update
      @stache = Stache.find(params[:id])
      if @stache.update(stache_params)
        flash[:notice] = "#{@stache.name} updated"
        redirect_to admin_staches_path
      else
        render "edit"
      end
    end

    def retire
      Stache.update(params[:stache_id], retired: true)
      redirect_to admin_staches_path
    end

    def activate
      Stache.update(params[:stache_id], retired: false)
      redirect_to admin_staches_path
    end

    private

    def stache_params
      params.require(:stache).permit(:name, :description, :price, :image_url,
                                     :categories, :retired)
    end
  end
end

app/controllers/staches_controller.rb
class StachesController < ApplicationController
  helper :headshot

  def index
    @staches = Stache.all
  end

  def show
    @stache = Stache.find(params[:id])
    session[:cam_stache_id] = @stache.id
  end

  def stached
    @stache = Stache.find(params[:stache_id])
    @photo = current_user.headshot_photos.last
  end

end

app/helpers/staches_helper.rb
module StachesHelper
end

app/views/admin/staches/_form.html.erb
<div class="container">
  <%= form_for([:admin, @stache]) do |f| %>

    <%= render "shared/error_messages", object: f.object %>

    <%= f.text_field :name %>
    <%= f.label :name %>

    <%= f.text_field :description %>
    <%= f.label :description %>

    <%= f.number_field :price %>
    <%= f.label :price %>

    <%= f.text_field :image_url %>
    <%= f.label :image_url, "Image Url" %>
    <br>
    <br>
    <%= f.label :categories %>
    <%= f.collection_check_boxes :categories, Category.all, :id, :title, include_hidden: false do |b| %>
     <div class="categories-checkboxes">
       <%= b.check_box %>
       <%= b.label %>
     </div>
      <% end %>

    <br>
    <%= f.label :retired, "Status" %>
    <br>
    <%= f.check_box :retired %>
    <%= f.label :retired, "Retired?" %>
    <br>
    <br>
    <%= f.submit yield(:button_text), class: "btn light-green darken-4"%>
  <% end %>
</div>

app/views/admin/staches/edit.html.erb
<h4>Make That Stache Even Stachier</h4>
<% provide(:button_text, "Update Stache") %>
<%= render "form" %>

app/views/admin/staches/index.html.erb
<div class="container">
<h4>You are the Stache Master</h4>
<%= link_to "Add New Stache", new_admin_stache_path, class: "btn light-green darken-4" %>
<table>
  <thead>
    <tr>
      <th data-field="image">Image</th>
      <th data-field="name">Name</th>
      <th data-field="description">Description</th>
      <th data-field="price">Price</th>
      <th data-field="status">Status</th>
      <th data-field="actions">Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @staches.each do |stache| %>
    <div id="stache-<%= stache.id %>">
      <tr>
        <td><%= image_tag(stache.image_url, width: "50%")  %></td>
        <td><%= link_to stache.name, stache, class: "btn light-green darken-4" %></td>
        <td><%= stache.description %></td>
        <td>$<%= stache.price %></td>
        <td><%= stache.status %></td>
        <td>
          <%= link_to "Edit", edit_admin_stache_path(stache) %>
          <%= link_to "Retire", admin_retire_stache_path(stache_id: stache.id), method: :put,
                      id: "stache-#{stache.id}-retire" unless stache.retired? %>
          <%= link_to "Activate", admin_activate_stache_path(stache_id: stache.id), method: :put,
                      id: "stache-#{stache.id}-activate" if stache.retired? %>
        </td>
      </tr>
    </div>
    <% end %>
  </tbody>
</table>
</div>

app/views/admin/staches/new.html.erb
<div class="container">
  <h4 class="center">Brand Spankin' New Stache</h4>
  <% provide(:button_text, "Create New Stache") %>
  <%= render "form" %>
</div>